"use client";

import Link from "next/link";
import React, { ChangeEvent, useMemo, useState } from "react";

type AssetClass = "Residential" | "Commercial" | "Land";
type ToastKind = "success" | "error" | "info";
type Toast = { show: boolean; kind: ToastKind; title: string; message: string };

type DealRoom = Record<string, any> & { id: string; kind: "deal"; createdAt: string; updatedAt: string };

const ROOM_KEYS = ["vaultforge_clean_deal_rooms", "vaultforge_deal_rooms", "vaultforge_rooms_deals", "vf_deal_rooms"];
const emptyToast: Toast = { show: false, kind: "info", title: "", message: "" };
const STATES = ["GA", "TN", "AL", "FL", "NC", "SC", "TX"];
const CONTACT_OPTIONS = ["VaultForge Message", "Phone", "Email", "Text"];
const ROLE_OPTIONS = ["Owner", "Wholesaler", "Agent", "Broker", "Investor", "Operator", "Lender", "Contractor", "Developer"];
const ROUTE_OPTIONS = ["Buyer", "Investor", "Lender", "Operator", "Contractor", "Broker", "JV Partner", "Developer", "Property Manager", "Capital Partner", "Boots On Ground"];
const URGENCY_OPTIONS = ["Low", "Normal", "High", "Critical", "Need answer today", "Need close fast"];
const OCCUPANCY_OPTIONS = ["Unknown", "Vacant", "Owner Occupied", "Tenant Occupied", "Partially Occupied", "Under Construction"];
const ISSUE_OPTIONS = ["None Known", "Title", "Probate", "Code", "Permits", "Tenant", "Foundation", "Roof", "Fire Damage", "Water Damage", "Funding Gap", "Contractor Problem", "Access Problem", "Lien", "Environmental"];
const ACCESS_OPTIONS = ["Unknown", "Drive By", "Appointment", "Lockbox", "Owner Access", "Tenant Notice Needed", "No Access Yet"];
const DOC_OPTIONS = ["Photos", "CMA", "Appraisal", "Inspection", "Survey", "Lease", "Rent Roll", "Plans", "Permits", "Title Work", "Seller Disclosure", "Tax Card"];
const STRATEGY_OPTIONS = ["Flip", "Buy & Hold", "Wholesale", "Development", "JV", "Debt", "Equity", "Value Add", "Entitlement", "Build To Rent", "STR", "Land Play"];
const CAPITAL_NEEDS = ["Cash Buyer", "Debt", "Equity", "JV Partner", "Hard Money", "Private Lender", "Bridge", "DSCR", "Proof Of Funds", "Fast Close", "No Capital Needed"];

function makeId() { return `deal_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`; }
function toggle(values: string[], value: string) { return values.includes(value) ? values.filter((x) => x !== value) : [...values, value]; }
function moneyLabel(value: string) { const clean = value.replace(/[^0-9.]/g, ""); if (!clean) return "not listed"; const num = Number(clean); return Number.isFinite(num) ? `$${num.toLocaleString()}` : value; }
function readArray(key: string): DealRoom[] { try { const raw = window.localStorage.getItem(key); const parsed = raw ? JSON.parse(raw) : []; return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
function syncDeal(deal: DealRoom) { ROOM_KEYS.forEach((key) => { const rows = readArray(key).filter((item) => String(item.id || item.roomId || item.dealId) !== deal.id); window.localStorage.setItem(key, JSON.stringify([deal, ...rows])); }); window.localStorage.setItem(`vaultforge_clean_deal_room_${deal.id}`, JSON.stringify(deal)); window.localStorage.setItem(`vaultforge_deal_room_${deal.id}`, JSON.stringify(deal)); window.localStorage.setItem(`vf_deal_room_${deal.id}`, JSON.stringify(deal)); window.dispatchEvent(new Event("vaultforge-deal-change")); }

const page: React.CSSProperties = { minHeight: "100vh", background: "#05070d", color: "#f7f7fb", padding: 18, fontFamily: "Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif" };
const wrap: React.CSSProperties = { maxWidth: 1180, margin: "0 auto", paddingBottom: 70 };
const card: React.CSSProperties = { background: "linear-gradient(180deg,#080d19,#050816)", border: "1px solid rgba(245,197,66,.28)", borderRadius: 26, padding: 28, marginBottom: 22 };
const eyebrow: React.CSSProperties = { color: "#ffd45a", textTransform: "uppercase", letterSpacing: 8, fontWeight: 900, fontSize: 14, marginBottom: 14 };
const h1: React.CSSProperties = { fontSize: "clamp(42px,7vw,78px)", lineHeight: .92, letterSpacing: -4, margin: "0 0 18px", fontWeight: 950 };
const sub: React.CSSProperties = { color: "#c9d0dc", fontSize: 20, lineHeight: 1.4, margin: 0 };
const row: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(230px,1fr))", gap: 16, marginTop: 16 };
const input: React.CSSProperties = { width: "100%", boxSizing: "border-box", borderRadius: 18, border: "1px solid rgba(207,216,230,.18)", background: "#121724", color: "#f6f7fb", padding: "17px 18px", fontSize: 16, outline: "none" };
const label: React.CSSProperties = { display: "block", color: "#ffd45a", fontSize: 13, letterSpacing: 2.5, textTransform: "uppercase", fontWeight: 900, marginBottom: 8 };
const chipWrap: React.CSSProperties = { display: "flex", flexWrap: "wrap", gap: 10, marginTop: 12 };
const chip: React.CSSProperties = { border: "1px solid rgba(207,216,230,.18)", background: "#171c29", color: "#f9fbff", borderRadius: 999, padding: "12px 16px", fontWeight: 900, cursor: "pointer" };
const chipActive: React.CSSProperties = { ...chip, background: "#ffdc68", color: "#111319", borderColor: "#ffdc68" };
const btn: React.CSSProperties = { border: "1px solid rgba(207,216,230,.18)", background: "#171c29", color: "#f7f7fb", borderRadius: 999, padding: "13px 18px", fontWeight: 950, textDecoration: "none", cursor: "pointer" };
const gold: React.CSSProperties = { ...btn, border: 0, background: "#ffdc68", color: "#10131a" };
const red: React.CSSProperties = { ...btn, background: "#271016", borderColor: "rgba(255,70,70,.48)", color: "#ffaaaa" };

export default function DealCreatePage() {
  const [assetClass, setAssetClass] = useState<AssetClass>("Residential");
  const [toast, setToast] = useState<Toast>(emptyToast);
  const [saving, setSaving] = useState(false);
  const [savedId, setSavedId] = useState("");
  const [photoFile, setPhotoFile] = useState<File | null>(null);
  const [photoPreview, setPhotoPreview] = useState("");
  const [photoUrl, setPhotoUrl] = useState("");
  const [routeTo, setRouteTo] = useState<string[]>(["Buyer", "Investor"]);
  const [knownIssues, setKnownIssues] = useState<string[]>(["None Known"]);
  const [docs, setDocs] = useState<string[]>(["Photos"]);
  const [strategies, setStrategies] = useState<string[]>(["Value Add"]);
  const [capitalNeeds, setCapitalNeeds] = useState<string[]>(["Cash Buyer"]);
  const [form, setForm] = useState({ title:"", state:"GA", city:"", county:"", address:"", askingPrice:"", arv:"", repairs:"", equitySpread:"", beds:"", baths:"", sqft:"", acres:"", units:"", buildingSize:"", zoning:"", contactName:"", contactPhone:"", contactEmail:"", bestContact:"VaultForge Message", submitterRole:"Owner", urgency:"High", occupancy:"Unknown", access:"Unknown", assignmentFee:"", deadline:"", notes:"", privateAiNotes:"", sellerMotivation:"", riskNotes:"" });
  function update(name: string, value: string) { setForm((c) => ({ ...c, [name]: value })); }
  function show(kind: ToastKind, title: string, message: string) { setToast({ show: true, kind, title, message }); if (kind === "success") window.setTimeout(() => setToast(emptyToast), 2600); }
  function handlePhoto(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) { show("error", "Photo error", "Choose an image file."); return; } setPhotoFile(file); const reader = new FileReader(); reader.onload = () => setPhotoPreview(String(reader.result || "")); reader.readAsDataURL(file); }
  async function uploadPhoto(roomId: string) { if (!photoFile) return ""; const data = new FormData(); data.append("file", photoFile); data.append("roomId", roomId); const res = await fetch("/api/uploads/deal", { method: "POST", body: data }); const json = await res.json().catch(() => ({})); if (!res.ok || !json?.ok) throw new Error(json?.error || "Photo upload failed. Check Supabase bucket vaultforge-deal-photos."); return String(json.photoUrl || ""); }
  const aiRead = useMemo(() => { const location = [form.city, form.county, form.state].filter(Boolean).join(", ") || "market not listed"; return `Market ${location}. ${assetClass} opportunity. Ask ${moneyLabel(form.askingPrice)}, ARV/value ${moneyLabel(form.arv)}, work ${moneyLabel(form.repairs)}. Strategy ${strategies.join(", ") || "not selected"}. Capital need ${capitalNeeds.join(", ") || "not selected"}. Route to ${routeTo.join(", ")}. Urgency ${form.urgency}. Issues ${knownIssues.join(", ")}. Access ${form.access}. Contact through ${form.bestContact}.`; }, [assetClass, form, routeTo, knownIssues, strategies, capitalNeeds]);
  function buildDeal(id: string, finalPhoto: string): DealRoom { const now = new Date().toISOString(); const signalSummary = `${assetClass} signal in ${[form.city, form.county, form.state].filter(Boolean).join(", ")}. Ask ${moneyLabel(form.askingPrice)}, ARV/value ${moneyLabel(form.arv)}, repair/work ${moneyLabel(form.repairs)}. AI should route by state, county, asset, strategy, urgency, capital need, and execution lane.`; return { id, kind:"deal", assetClass, title:form.title.trim(), state:form.state, city:form.city.trim(), county:form.county.trim(), address:form.address.trim(), askingPrice:form.askingPrice.trim(), arv:form.arv.trim(), repairs:form.repairs.trim(), equitySpread:form.equitySpread.trim(), beds:form.beds.trim(), baths:form.baths.trim(), sqft:form.sqft.trim(), acres:form.acres.trim(), units:form.units.trim(), buildingSize:form.buildingSize.trim(), zoning:form.zoning.trim(), contactName:form.contactName.trim(), contactPhone:form.contactPhone.trim(), contactEmail:form.contactEmail.trim(), bestContact:form.bestContact, submitterRole:form.submitterRole, routeTo, strategies, capitalNeeds, urgency:form.urgency, occupancy:form.occupancy, knownIssues, access:form.access, docs, assignmentFee:form.assignmentFee.trim(), deadline:form.deadline.trim(), notes:form.notes.trim(), privateAiNotes:form.privateAiNotes.trim(), sellerMotivation:form.sellerMotivation.trim(), riskNotes:form.riskNotes.trim(), aiRead, signalSummary, photoUrl:finalPhoto, imageUrl:finalPhoto, publicUrl:finalPhoto, photo:finalPhoto, photoName:photoFile?.name || "", createdAt:now, updatedAt:now, roomState:"active" }; }
  async function saveDeal() { if (saving) return; setSaving(true); try { if (!form.title.trim()) throw new Error("Add a deal name/title."); if (!form.city.trim() || !form.state.trim()) throw new Error("Add city and state."); if (!form.contactName.trim() && !form.contactPhone.trim() && !form.contactEmail.trim()) throw new Error("Add at least one contact field."); const id = makeId(); let finalPhoto = photoUrl; if (photoFile && !finalPhoto) finalPhoto = await uploadPhoto(id); setPhotoUrl(finalPhoto); const deal = buildDeal(id, finalPhoto); syncDeal(deal); setSavedId(id); show("success", finalPhoto ? "Deal saved with photo" : "Deal saved", "Deal Room is live on the board. Open Deal Rooms or open the new room below."); } catch (e) { show("error", "Deal not saved", e instanceof Error ? e.message : "Unknown error."); } finally { setSaving(false); } }
  return <main style={page}><div style={wrap}><nav style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:18}}><Link href="/command" style={btn}>Command</Link><Link href="/deal-rooms" style={gold}>Deal Rooms</Link><Link href="/profile" style={btn}>Profile</Link><Link href="/" style={red}>Exit</Link></nav>{toast.show && <div style={{position:"fixed",top:18,left:"50%",transform:"translateX(-50%)",zIndex:9999,width:"min(92vw,760px)",borderRadius:20,padding:"16px 18px",background:toast.kind==="success"?"#102818":toast.kind==="error"?"#2b1015":"#111827",border:toast.kind==="success"?"1px solid rgba(101,255,151,.5)":"1px solid rgba(255,88,88,.55)",boxShadow:"0 18px 70px rgba(0,0,0,.55)"}}><strong style={{fontSize:18}}>{toast.title}</strong><div style={{color:"#dce4ef",marginTop:4}}>{toast.message}</div></div>}
  <section style={card}><div style={eyebrow}>Deal Opportunity Brain</div><h1 style={h1}>Create the room intelligence.</h1><p style={sub}>This intake captures the photo, signal, numbers, contact, capital need, routing lanes, risk, and AI context used by VaultForge Deal Rooms.</p></section>
  <section style={card}><div style={eyebrow}>Asset Class</div><div style={chipWrap}>{(["Residential","Commercial","Land"] as AssetClass[]).map((x)=><button key={x} type="button" onClick={()=>setAssetClass(x)} style={assetClass===x?chipActive:chip}>{x}</button>)}</div></section>
  <section style={card}><div style={eyebrow}>Photo + AI Read</div>{photoPreview ? <img src={photoPreview} alt="Preview" style={{width:"100%",maxHeight:380,objectFit:"cover",borderRadius:22,border:"1px solid rgba(207,216,230,.2)",marginBottom:12}}/> : <div style={{border:"1px dashed rgba(207,216,230,.25)",borderRadius:22,padding:50,textAlign:"center",color:"#c9d0dc",marginBottom:12}}>Upload deal photo</div>}<input type="file" accept="image/*" onChange={handlePhoto}/><div style={{...card,marginTop:18,marginBottom:0,padding:18}}><div style={eyebrow}>Live AI Room Read</div><p style={{...sub,fontSize:18}}>{aiRead}</p></div></section>
  <section style={card}><div style={eyebrow}>{assetClass} Facts</div><div style={row}><Field name="Deal Name / Title" value={form.title} onChange={(v)=>update("title",v)} /><Select name="State" value={form.state} options={STATES} onChange={(v)=>update("state",v)} /><Field name="City" value={form.city} onChange={(v)=>update("city",v)} /><Field name="County" value={form.county} onChange={(v)=>update("county",v)} /><Field name="Address / Location" value={form.address} onChange={(v)=>update("address",v)} /><Field name="Ask Price" value={form.askingPrice} onChange={(v)=>update("askingPrice",v)} /><Field name="ARV / Value" value={form.arv} onChange={(v)=>update("arv",v)} /><Field name="Repairs / Work" value={form.repairs} onChange={(v)=>update("repairs",v)} /><Field name="Equity Spread" value={form.equitySpread} onChange={(v)=>update("equitySpread",v)} />{assetClass==="Residential" && <><Field name="Beds" value={form.beds} onChange={(v)=>update("beds",v)} /><Field name="Baths" value={form.baths} onChange={(v)=>update("baths",v)} /><Field name="Sqft" value={form.sqft} onChange={(v)=>update("sqft",v)} /></>}{assetClass==="Commercial" && <><Field name="Units" value={form.units} onChange={(v)=>update("units",v)} /><Field name="Building Size" value={form.buildingSize} onChange={(v)=>update("buildingSize",v)} /><Field name="Zoning" value={form.zoning} onChange={(v)=>update("zoning",v)} /></>}{assetClass==="Land" && <><Field name="Acres" value={form.acres} onChange={(v)=>update("acres",v)} /><Field name="Zoning" value={form.zoning} onChange={(v)=>update("zoning",v)} /></>}</div></section>
  <section style={card}><div style={eyebrow}>Contact + Routing Control</div><div style={row}><Field name="Contact Name" value={form.contactName} onChange={(v)=>update("contactName",v)} /><Field name="Phone" value={form.contactPhone} onChange={(v)=>update("contactPhone",v)} /><Field name="Email" value={form.contactEmail} onChange={(v)=>update("contactEmail",v)} /><Field name="Assignment Fee / Spread" value={form.assignmentFee} onChange={(v)=>update("assignmentFee",v)} /><Field name="Deadline / Close Date" value={form.deadline} onChange={(v)=>update("deadline",v)} /></div><Choice title="Best Contact" options={CONTACT_OPTIONS} value={form.bestContact} onPick={(v)=>update("bestContact",v)} /><Choice title="Submitter Role" options={ROLE_OPTIONS} value={form.submitterRole} onPick={(v)=>update("submitterRole",v)} /><Choice title="Urgency" options={URGENCY_OPTIONS} value={form.urgency} onPick={(v)=>update("urgency",v)} /><Choice title="Occupancy" options={OCCUPANCY_OPTIONS} value={form.occupancy} onPick={(v)=>update("occupancy",v)} /><Choice title="Access" options={ACCESS_OPTIONS} value={form.access} onPick={(v)=>update("access",v)} /><Multi title="Route This To" options={ROUTE_OPTIONS} values={routeTo} onToggle={(v)=>setRouteTo((c)=>toggle(c,v))}/><Multi title="Strategy" options={STRATEGY_OPTIONS} values={strategies} onToggle={(v)=>setStrategies((c)=>toggle(c,v))}/><Multi title="Capital Need" options={CAPITAL_NEEDS} values={capitalNeeds} onToggle={(v)=>setCapitalNeeds((c)=>toggle(c,v))}/><Multi title="Known Issues" options={ISSUE_OPTIONS} values={knownIssues} onToggle={(v)=>setKnownIssues((c)=>toggle(c,v))}/><Multi title="Available Docs" options={DOC_OPTIONS} values={docs} onToggle={(v)=>setDocs((c)=>toggle(c,v))}/></section>
  <section style={card}><div style={eyebrow}>AI Notes + Risk</div><div style={row}><Text name="Seller Motivation" value={form.sellerMotivation} onChange={(v)=>update("sellerMotivation",v)}/><Text name="Risk Notes" value={form.riskNotes} onChange={(v)=>update("riskNotes",v)}/><Text name="Private AI Notes" value={form.privateAiNotes} onChange={(v)=>update("privateAiNotes",v)}/><Text name="Room Notes" value={form.notes} onChange={(v)=>update("notes",v)}/></div></section>
  <section style={card}><div style={eyebrow}>Save Deal Room</div><p style={{...sub,fontSize:18}}>This writes the full VaultForge brain object and syncs it to every clean Deal Room key.</p><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:18}}><button type="button" onClick={saveDeal} disabled={saving} style={gold}>{saving?"Saving...":"Save Deal Room"}</button><Link href="/deal-rooms" style={btn}>Open Deal Rooms</Link>{savedId && <Link href={`/deal-rooms/${savedId}`} style={btn}>Open New Room</Link>}</div></section>
  </div></main>;
}
function Field({name,value,onChange}:{name:string;value:string;onChange:(v:string)=>void}){return <label><span style={label}>{name}</span><input style={input} value={value} onChange={(e)=>onChange(e.target.value)} placeholder={name}/></label>}
function Text({name,value,onChange}:{name:string;value:string;onChange:(v:string)=>void}){return <label><span style={label}>{name}</span><textarea style={{...input,minHeight:120,resize:"vertical"}} value={value} onChange={(e)=>onChange(e.target.value)} placeholder={name}/></label>}
function Select({name,value,options,onChange}:{name:string;value:string;options:string[];onChange:(v:string)=>void}){return <label><span style={label}>{name}</span><select style={input} value={value} onChange={(e)=>onChange(e.target.value)}>{options.map((x)=><option key={x} value={x}>{x}</option>)}</select></label>}
function Choice({title,options,value,onPick}:{title:string;options:string[];value:string;onPick:(v:string)=>void}){return <div style={{marginTop:22}}><div style={label}>{title}</div><div style={chipWrap}>{options.map((x)=><button key={x} type="button" style={value===x?chipActive:chip} onClick={()=>onPick(x)}>{x}</button>)}</div></div>}
function Multi({title,options,values,onToggle}:{title:string;options:string[];values:string[];onToggle:(v:string)=>void}){return <div style={{marginTop:22}}><div style={label}>{title}</div><div style={chipWrap}>{options.map((x)=><button key={x} type="button" style={values.includes(x)?chipActive:chip} onClick={()=>onToggle(x)}>{x}</button>)}</div></div>}
