"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type PainRoom = Record<string, any> & { id: string; photoUrls?: string[]; routingNeeds?: string[]; blockers?: string[]; painTypes?: string[]; urgency?: string[] };
type RoomState = "active" | "saved" | "archived" | "deleted";

const STORAGE_KEYS = ["vaultforge_clean_pain_rooms_v1", "vaultforge_pain_rooms", "vf_pain_rooms"];
const STATE_KEY = "vaultforge_clean_room_states";

function readArray(key: string): any[] { try { const parsed = JSON.parse(window.localStorage.getItem(key) || "[]"); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
function writeArray(key: string, rows: any[]) { window.localStorage.setItem(key, JSON.stringify(rows)); }
function idOf(row: any) { return String(row?.id || row?.painId || row?.roomId || ""); }
function readStates(): Record<string, RoomState> { try { return JSON.parse(window.localStorage.getItem(STATE_KEY) || "{}"); } catch { return {}; } }
function writeStates(states: Record<string, RoomState>) { window.localStorage.setItem(STATE_KEY, JSON.stringify(states)); }
function uniqueRooms(): PainRoom[] { const states = readStates(); const map = new Map<string, PainRoom>(); STORAGE_KEYS.flatMap(readArray).forEach((row) => { const id = idOf(row); if (!id || map.has(id)) return; const roomState = states[`pain:${id}`] || states[id] || row.roomState || "active"; if (roomState === "deleted" || roomState === "archived") return; map.set(id, { ...row, id, roomState }); }); return Array.from(map.values()).sort((a,b)=>String(b.createdAt||b.updatedAt||"").localeCompare(String(a.createdAt||a.updatedAt||""))); }
function money(value:any){const clean=String(value||"").replace(/[^0-9.]/g,""); if(!clean)return "Not listed"; const n=Number(clean); return Number.isNaN(n)?String(value):`$${n.toLocaleString()}`;}
function arr(row:any,key:string){const v=row?.[key]; return Array.isArray(v)?v.map(String):typeof v==="string"&&v.trim()?v.split(",").map((x)=>x.trim()).filter(Boolean):[];}
function firstPhoto(room:PainRoom){const photos=Array.isArray(room.photoUrls)?room.photoUrls:[]; return String(room.photoUrl||room.photo||photos[0]||"");}
function stateCount(rooms:PainRoom[]){const counts:Record<string,number>={}; rooms.forEach((r)=>{const s=String(r.state||"Unknown"); counts[s]=(counts[s]||0)+1;}); return counts;}
function syncState(room:PainRoom,state:RoomState){const id=room.id; const states=readStates(); states[`pain:${id}`]=state; writeStates(states); STORAGE_KEYS.forEach((key)=>{const rows=readArray(key).map((r)=>idOf(r)===id?{...r,roomState:state,updatedAt:new Date().toISOString()}:r); writeArray(key,rows);}); window.dispatchEvent(new Event("vaultforge-pain-change"));}

export default function VaultForgePainRoomsClient(){
  const [rooms,setRooms]=useState<PainRoom[]>([]);
  function refresh(){setRooms(uniqueRooms());}
  useEffect(()=>{refresh(); window.addEventListener("vaultforge-pain-change",refresh); return()=>window.removeEventListener("vaultforge-pain-change",refresh);},[]);
  const metrics=useMemo(()=>({total:rooms.length, emergency:rooms.filter(r=>arr(r,"urgency").includes("Emergency")).length, capital:rooms.filter(r=>arr(r,"blockers").some(x=>x.toLowerCase().includes("cash")||x.toLowerCase().includes("lender"))).length, states:stateCount(rooms)}),[rooms]);
  return <>
    <section style={grid4}><Metric label="Active Rooms" value={metrics.total}/><Metric label="Emergency" value={metrics.emergency}/><Metric label="Capital Pressure" value={metrics.capital}/><Metric label="States" value={Object.keys(metrics.states).length}/></section>
    <section style={card}><div style={eyebrow}>State Count</div><div style={chips}>{Object.entries(metrics.states).map(([s,c])=><span key={s} style={pill}>{s}: {c}</span>)}</div></section>
    <section style={card}><div style={eyebrow}>Pain Solution Rooms</div>{!rooms.length?<p style={sub}>No Pain Solution Rooms yet. Use Pain Intake to create one.</p>:null}<div style={roomGrid}>{rooms.map(room=><article key={room.id} style={roomCard}>{firstPhoto(room)?<img src={firstPhoto(room)} alt={room.title||"Pain room"} style={photo}/>:<div style={photoEmpty}>No photo</div>}<div style={eyebrow}>{room.assetClass||"Pain Room"}</div><h2 style={title}>{room.title||"Untitled Pain Room"}</h2><p style={subSmall}>{[room.city,room.county,room.state].filter(Boolean).join(", ")||"Market not listed"}</p><p style={facts}>Need: {money(room.amountNeeded)}<br/>Value: {money(room.propertyValue||room.arv)}<br/>Blockers: {arr(room,"blockers").join(", ")||"Not selected"}<br/>Route: {arr(room,"routingNeeds").join(", ")||"Not selected"}</p><div style={actions}><Link href={`/pain-rooms/${encodeURIComponent(room.id)}`} style={goldBtn}>Open Room</Link><Link href={`/messages?type=pain&room=${encodeURIComponent(room.id)}&subject=${encodeURIComponent(`Pain: ${room.title||"Pain Room"}`)}`} style={btn}>Message</Link><button type="button" onClick={()=>syncState(room,"saved")} style={btn}>Save</button><button type="button" onClick={()=>syncState(room,"archived")} style={btn}>Archive</button><button type="button" onClick={()=>syncState(room,"deleted")} style={redBtn}>Delete</button></div></article>)}</div></section>
  </>;
}
function Metric({label,value}:{label:string;value:number}){return <div style={metric}><span>{label}</span><strong>{value}</strong></div>}

const card:React.CSSProperties={background:"linear-gradient(180deg,#080d19,#050816)",border:"1px solid rgba(245,197,66,.28)",borderRadius:26,padding:28,marginBottom:22}; const eyebrow:React.CSSProperties={color:"#ffd45a",textTransform:"uppercase",letterSpacing:8,fontWeight:900,fontSize:18,marginBottom:14}; const sub:React.CSSProperties={color:"#c9d0dc",fontSize:21,lineHeight:1.35,margin:0}; const subSmall:React.CSSProperties={color:"#c9d0dc",fontSize:18,lineHeight:1.35,margin:"0 0 14px"}; const grid4:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:14,marginBottom:22}; const metric:React.CSSProperties={...card,marginBottom:0,padding:20}; const chips:React.CSSProperties={display:"flex",flexWrap:"wrap",gap:10}; const pill:React.CSSProperties={border:"1px solid rgba(207,216,230,.18)",background:"#171c29",color:"#f7f7fb",borderRadius:999,padding:"12px 16px",fontWeight:900}; const roomGrid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:18}; const roomCard:React.CSSProperties={...card,marginBottom:0}; const photo:React.CSSProperties={width:"100%",height:230,objectFit:"cover",borderRadius:20,marginBottom:18,border:"1px solid rgba(207,216,230,.18)"}; const photoEmpty:React.CSSProperties={height:230,borderRadius:20,border:"1px dashed rgba(207,216,230,.25)",display:"grid",placeItems:"center",color:"#c9d0dc",marginBottom:18}; const title:React.CSSProperties={fontSize:34,lineHeight:1,letterSpacing:-2,margin:"0 0 8px",fontWeight:950}; const facts:React.CSSProperties={color:"#dce4ef",fontSize:18,lineHeight:1.45}; const actions:React.CSSProperties={display:"flex",gap:10,flexWrap:"wrap",marginTop:16}; const btn:React.CSSProperties={border:"1px solid rgba(207,216,230,.18)",background:"#171c29",color:"#f7f7fb",borderRadius:999,padding:"12px 16px",fontWeight:950,textDecoration:"none",cursor:"pointer"}; const goldBtn:React.CSSProperties={...btn,border:0,background:"#ffdc68",color:"#10131a"}; const redBtn:React.CSSProperties={...btn,background:"#271016",borderColor:"rgba(255,70,70,.48)",color:"#ffaaaa"};
