"use client";

import React from "react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type PainRoom = Record<string, any> & { id: string };
const STORAGE_KEYS = ["vaultforge_clean_pain_rooms_v1", "vaultforge_pain_rooms", "vaultforge_rooms_pain", "vf_pain_rooms"];
const STATE_KEY = "vaultforge_clean_room_states";
const card: React.CSSProperties = { border:"1px solid rgba(239,68,68,.30)", background:"radial-gradient(circle at top right, rgba(239,68,68,.15), transparent 28%),linear-gradient(145deg, rgba(35,8,8,.96), rgba(2,6,23,.99))", borderRadius:24, padding:16, display:"grid", gridTemplateColumns:"190px minmax(0,1fr)", gap:16 };
const btn: React.CSSProperties = { border:"1px solid rgba(207,216,230,.18)", background:"#171c29", color:"#f7f7fb", borderRadius:999, padding:"12px 15px", fontWeight:950, textDecoration:"none", display:"inline-block", cursor:"pointer" };
const redBtn: React.CSSProperties = { ...btn, background:"#ef4444", color:"#fff", border:0 };
function read<T>(key:string,f:T):T{try{const raw=window.localStorage.getItem(key);return raw?JSON.parse(raw):f}catch{return f}}
function write(key:string,v:any){window.localStorage.setItem(key,JSON.stringify(v))}
function id(room:PainRoom){return String(room.id||room.roomId||"")}
function arr(v:any){return Array.isArray(v)?v.map(String):typeof v==="string"&&v.trim()?v.split(",").map(x=>x.trim()).filter(Boolean):[]}
function val(room:PainRoom,keys:string[],fallback="Not listed"){for(const k of keys){const v=room?.[k]; if(v!==undefined&&v!==null&&String(v).trim())return String(v)} return fallback}
function money(v:string){const c=String(v||"").replace(/[^0-9.]/g,""); if(!c)return "Not listed"; const n=Number(c); return Number.isFinite(n)?`$${n.toLocaleString()}`:v}
function photo(room:PainRoom){return val(room,["photoUrl","imageUrl","publicUrl","photo"],"")}
function readRooms(){const map=new Map<string,PainRoom>(); for(const key of STORAGE_KEYS){const rows=read<PainRoom[]>(key,[]); if(Array.isArray(rows)) rows.forEach(r=>{if(id(r))map.set(id(r),r)})} return Array.from(map.values()).sort((a,b)=>String(b.createdAt||"").localeCompare(String(a.createdAt||"")))}
function setState(room:PainRoom,state:"saved"|"archived"|"deleted"){const states=read<Record<string,string>>(STATE_KEY,{}); states[id(room)]=state; write(STATE_KEY,states); window.dispatchEvent(new Event("vaultforge-pain-change"))}
function PainCard({room}:{room:PainRoom}){const img=photo(room); const pressure=Number(room.pressureScore||42); const routes=arr(room.routingNeeds); return <article style={card}><div style={{minHeight:170,borderRadius:18,overflow:"hidden",border:"1px solid rgba(239,68,68,.25)",background:"rgba(127,29,29,.18)",display:"grid",placeItems:"center",color:"#ef4444",fontSize:44,fontWeight:950}}>{img?<img src={img} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:"!"}</div><div><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><div style={{color:"#fca5a5",letterSpacing:4,fontWeight:950,textTransform:"uppercase",fontSize:12}}>Pain Solution Room</div><h2 style={{fontSize:30,lineHeight:1,margin:"8px 0",color:"#fff"}}>{val(room,["title"],"Untitled Pain Room")}</h2><p style={{color:"#c9d0dc",margin:0}}>{[val(room,["city"],""),val(room,["county"],""),val(room,["state"],"")].filter(Boolean).join(" • ")||"Market not listed"}</p></div><div style={{textAlign:"right"}}><strong style={{display:"block",color:"#ef4444",fontSize:38,lineHeight:1}}>{pressure}</strong><span style={{color:"#fecaca",fontSize:11,letterSpacing:2,textTransform:"uppercase",fontWeight:900}}>Pressure</span></div></div><div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:12}}>{[...arr(room.painTypes),...arr(room.urgency),money(val(room,["amountNeeded"],""))].filter(Boolean).slice(0,8).map(x=><span key={x} style={{border:"1px solid rgba(239,68,68,.22)",background:"rgba(127,29,29,.18)",color:"#fee2e2",borderRadius:999,padding:"7px 10px",fontSize:12,fontWeight:850}}>{x}</span>)}</div><section style={{border:"1px solid rgba(239,68,68,.24)",background:"rgba(255,255,255,.045)",borderRadius:18,padding:14,marginTop:14}}><div style={{color:"#fca5a5",letterSpacing:3,fontWeight:950,fontSize:12,textTransform:"uppercase"}}>AI Execution Read</div><p style={{color:"#c9d0dc",margin:"8px 0 0"}}>{val(room,["aiExecutionRead","dmaicSummary","notes"],`Routes: ${routes.join(", ")||"not selected"}`)}</p></section><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:14}}><Link style={redBtn} href={`/pain-rooms/${encodeURIComponent(id(room))}`}>Open Room</Link><Link style={btn} href={`/messages?room=${encodeURIComponent(id(room))}&type=pain&subject=${encodeURIComponent(`Pain Room: ${val(room,["title"],"Untitled Pain Room")}`)}`}>Message Owner</Link><button type="button" style={btn} onClick={()=>setState(room,"saved")}>Save</button><button type="button" style={btn} onClick={()=>setState(room,"archived")}>Archive</button><button type="button" style={{...btn,background:"#271016",borderColor:"rgba(255,70,70,.48)",color:"#ffaaaa"}} onClick={()=>setState(room,"deleted")}>Delete</button></div></div></article>}
export default function VaultForgePainRoomsClient(){const [rooms,setRooms]=useState<PainRoom[]>([]); function refresh(){setRooms(readRooms())} useEffect(()=>{refresh();window.addEventListener("vaultforge-pain-change",refresh);window.addEventListener("storage",refresh);return()=>{window.removeEventListener("vaultforge-pain-change",refresh);window.removeEventListener("storage",refresh)}},[]); const m=useMemo(()=>({active:rooms.length,emergency:rooms.filter(r=>arr(r.urgency).includes("Emergency")).length,high:rooms.filter(r=>arr(r.urgency).includes("High")).length,capital:rooms.filter(r=>arr(r.blockers).includes("Capital")).length}),[rooms]); return <><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12,marginBottom:18}}>{[["Active",m.active],["Emergency",m.emergency],["High",m.high],["Capital",m.capital]].map(([a,b])=><div key={a} style={{border:"1px solid rgba(239,68,68,.25)",borderRadius:18,padding:16,background:"rgba(255,255,255,.04)"}}><span style={{color:"#fecaca",fontSize:12,letterSpacing:2,textTransform:"uppercase",fontWeight:900}}>{a}</span><strong style={{display:"block",fontSize:34,color:"#fff"}}>{b}</strong></div>)}</section><section style={{display:"grid",gap:14}}>{rooms.length?rooms.map(r=><PainCard key={id(r)} room={r}/>):<p style={{color:"#c9d0dc",fontSize:20}}>No saved Pain Rooms yet. Use Pain Intake to create a Lean Six Sigma solution room.</p>}</section></>}
