"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";

type PainRoom = Record<string, any> & { id: string };
type Profile = Record<string, any>;

const STORAGE_KEY = "vaultforge_clean_pain_rooms_v1";
const ROOM_KEY_PREFIX = "vaultforge_clean_pain_room_";
const PROFILE_KEY = "vaultforge_profile_v2";
const STATE_KEY = "vaultforge_clean_room_states";

const page: React.CSSProperties = { minHeight: "100vh", background: "#05070d", color: "#f7f7fb", padding: 18, fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif" };
const wrap: React.CSSProperties = { maxWidth: 1180, margin: "0 auto", paddingBottom: 70 };
const card: React.CSSProperties = { background: "linear-gradient(180deg,#150808,#070810)", border: "1px solid rgba(255,90,90,.30)", borderRadius: 26, padding: 28, marginBottom: 22 };
const goldCard: React.CSSProperties = { ...card, background: "linear-gradient(180deg,#080d19,#050816)", border: "1px solid rgba(245,197,66,.28)" };
const eyebrow: React.CSSProperties = { color: "#ffaaaa", textTransform: "uppercase", letterSpacing: 7, fontWeight: 950, fontSize: 15, marginBottom: 14 };
const goldEye: React.CSSProperties = { ...eyebrow, color: "#ffd45a" };
const h1: React.CSSProperties = { fontSize: "clamp(42px,7vw,76px)", lineHeight: .92, letterSpacing: -4, margin: "0 0 18px", fontWeight: 950 };
const sub: React.CSSProperties = { color: "#c9d0dc", fontSize: 21, lineHeight: 1.38, margin: 0 };
const grid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(230px,1fr))", gap: 16 };
const btn: React.CSSProperties = { border: "1px solid rgba(207,216,230,.18)", background: "#171c29", color: "#f7f7fb", borderRadius: 999, padding: "13px 18px", fontWeight: 950, textDecoration: "none", display: "inline-block", cursor: "pointer" };
const goldBtn: React.CSSProperties = { ...btn, border: 0, background: "#ffdc68", color: "#10131a" };
const redBtn: React.CSSProperties = { ...btn, background: "#2b1015", borderColor: "rgba(255,88,88,.55)", color: "#ffb4b4" };

function readRooms(): PainRoom[] { try { const raw = window.localStorage.getItem(STORAGE_KEY); const parsed = raw ? JSON.parse(raw) : []; return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
function readStates(): Record<string, string> { try { return JSON.parse(window.localStorage.getItem(STATE_KEY) || "{}"); } catch { return {}; } }
function writeStates(states: Record<string, string>) { window.localStorage.setItem(STATE_KEY, JSON.stringify(states)); }
function readProfile(): Profile | null { try { const raw = window.localStorage.getItem(PROFILE_KEY); return raw ? JSON.parse(raw) : null; } catch { return null; } }
function findRoom(id: string): PainRoom | null { const byList = readRooms().find((room) => String(room.id) === id); if (byList) return byList; try { const raw = window.localStorage.getItem(`${ROOM_KEY_PREFIX}${id}`); return raw ? JSON.parse(raw) : null; } catch { return null; } }
function syncRoom(room: PainRoom) { const rooms = readRooms().filter((item) => String(item.id) !== String(room.id)); window.localStorage.setItem(STORAGE_KEY, JSON.stringify([room, ...rooms])); window.localStorage.setItem(`${ROOM_KEY_PREFIX}${room.id}`, JSON.stringify(room)); window.dispatchEvent(new Event("vaultforge-pain-change")); }
function arr(room: Record<string, any> | null, key: string) { const v = room?.[key]; return Array.isArray(v) ? v.map(String) : typeof v === "string" && v ? v.split(",").map((x) => x.trim()).filter(Boolean) : []; }
function val(room: Record<string, any> | null, key: string, fallback = "Not listed") { const v = room?.[key]; return v === undefined || v === null || !String(v).trim() ? fallback : String(v); }
function money(v: string) { const clean = String(v || "").replace(/[^0-9.]/g, ""); if (!clean) return "Not listed"; const n = Number(clean); return Number.isFinite(n) ? `$${n.toLocaleString()}` : v; }
function photoUrls(room: PainRoom | null) { const urls = arr(room, "photoUrls"); if (urls.length) return urls; const photos = room?.photos; if (Array.isArray(photos)) return photos.map((p) => String(p?.url || "")).filter(Boolean); const one = String(room?.photoUrl || room?.photo || ""); return one ? [one] : []; }
function fitScore(profile: Profile | null, room: PainRoom | null) { if (!profile || !room) return 0; let score = 35; const state = val(room, "state", ""); const asset = val(room, "assetClass", ""); const routes = arr(room, "routingNeeds"); const buyStates = arr(profile, "buyStates"); const alertStates = arr(profile, "alertStates"); const contactStates = arr(profile, "contactStates"); const assets = arr(profile, "assetTypes"); const types = arr(profile, "memberTypes"); const caps = arr(profile, "executionCapabilities").concat(arr(profile, "capitalRoles")); if ([...buyStates, ...alertStates, ...contactStates].includes(state)) score += 18; if (assets.some((x) => asset.toLowerCase().includes(x.toLowerCase()) || x.toLowerCase().includes(asset.toLowerCase()))) score += 15; if (routes.some((r) => types.join(" ").toLowerCase().includes(r.toLowerCase()))) score += 14; if (routes.some((r) => caps.join(" ").toLowerCase().includes(r.toLowerCase()))) score += 12; if (arr(profile, "preferredContact").length) score += 6; return Math.min(99, score); }

function Fact({ label, value }: { label: string; value: string }) { return <div style={{ background: "#121724", border: "1px solid rgba(207,216,230,.14)", borderRadius: 20, padding: 20 }}><div style={{ ...goldEye, fontSize: 12, letterSpacing: 4 }}>{label}</div><div style={{ fontSize: 22, fontWeight: 850 }}>{value || "Not listed"}</div></div>; }
function ChipList({ title, items, red = false }: { title: string; items: string[]; red?: boolean }) { return <section style={{ marginTop: 16 }}><div style={red ? eyebrow : goldEye}>{title}</div><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{items.length ? items.map((item) => <span key={item} style={{ border: red ? "1px solid rgba(255,90,90,.32)" : "1px solid rgba(245,197,66,.28)", background: red ? "rgba(255,90,90,.09)" : "rgba(245,197,66,.08)", borderRadius: 999, padding: "9px 12px", fontWeight: 850 }}>{item}</span>) : <span style={{ color: "#c9d0dc" }}>Not selected</span>}</div></section>; }

export default function PainRoomDetailPage() {
  const params = useParams();
  const id = decodeURIComponent(String(params?.id || ""));
  const [room, setRoom] = useState<PainRoom | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);

  useEffect(() => { setRoom(findRoom(id)); setProfile(readProfile()); }, [id]);

  function setRoomState(state: string) { if (!room) return; const states = readStates(); states[`pain:${room.id}`] = state; states[room.id] = state; writeStates(states); const next = { ...room, roomState: state, updatedAt: new Date().toISOString() }; syncRoom(next); setRoom(next); }

  const photos = photoUrls(room);
  const score = fitScore(profile, room);
  const subject = `Pain Room: ${val(room, "title", "Untitled Pain Room")}`;
  const dmaicSummary = useMemo(() => room ? `DEFINE: ${val(room,"title")}. MEASURE: pressure ${val(room,"pressureScore","--")}/100, amount needed ${money(val(room,"amountNeeded",""))}, deadline ${val(room,"deadline")}. ANALYZE: blockers ${arr(room,"blockers").join(", ") || "not selected"}; root cause ${arr(room,"rootCause").join(", ") || "not selected"}. IMPROVE: route to ${arr(room,"routingNeeds").join(", ") || "selected member profiles"}; solution lanes ${arr(room,"solutionLanes").join(", ") || "not selected"}. CONTROL: owner contact ${val(room,"bestContact")}, authority ${val(room,"authority")}, access ${val(room,"access")}.` : "", [room]);

  if (!room) return <main style={page}><div style={wrap}><Link href="/pain-rooms" style={goldBtn}>Back to Pain Rooms</Link><section style={card}><div style={eyebrow}>Pain Room</div><h1 style={h1}>Room not found.</h1><p style={sub}>This Pain Room was not found in local storage.</p></section></div></main>;

  return <main style={page}><div style={wrap}>
    <nav style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 18 }}><Link href="/command" style={btn}>Command</Link><Link href="/pain-rooms" style={goldBtn}>Pain Rooms</Link><Link href="/pain-intake" style={btn}>Create Pain</Link><Link href={`/messages?room=${encodeURIComponent(room.id)}&subject=${encodeURIComponent(subject)}`} style={btn}>Message Owner</Link><Link href="/" style={redBtn}>Exit</Link></nav>
    <section style={card}>{photos.length ? <div style={{ display: "grid", gridTemplateColumns: photos.length === 1 ? "1fr" : "repeat(auto-fit,minmax(180px,1fr))", gap: 12, marginBottom: 22 }}>{photos.slice(0,5).map((src, index) => <img key={src + index} src={src} alt={`Pain room photo ${index + 1}`} style={{ width: "100%", height: index === 0 ? 360 : 210, objectFit: "cover", borderRadius: 22, border: "1px solid rgba(255,255,255,.14)" }} />)}</div> : <div style={{ border: "1px dashed rgba(207,216,230,.25)", borderRadius: 24, padding: 70, textAlign: "center", color: "#c9d0dc", marginBottom: 24 }}>No photos saved for this room</div>}<div style={eyebrow}>{val(room,"assetClass","Pain Room")} • Pressure {val(room,"pressureScore","--")}/100</div><h1 style={h1}>{val(room,"title","Untitled Pain Room")}</h1><p style={sub}>{[room.city, room.county, room.state].filter(Boolean).join(" • ") || "Market not listed"}</p></section>
    <section style={goldCard}><div style={goldEye}>5S Cleanup Controls</div><div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}><button type="button" onClick={() => setRoomState("saved")} style={goldBtn}>Save</button><button type="button" onClick={() => setRoomState("archived")} style={btn}>Archive</button><button type="button" onClick={() => setRoomState("deleted")} style={redBtn}>Delete</button><span style={btn}>Current: {val(room,"roomState","active")}</span></div></section>
    <section style={card}><div style={eyebrow}>Six Sigma / Lean Black Belt Read</div><h2 style={{ fontSize: 38, margin: "0 0 14px" }}>DMAIC Solution Control</h2><p style={sub}>{dmaicSummary}</p><ChipList title="DMAIC Stage" items={arr(room,"processStage")} /><ChipList title="Root Cause" items={arr(room,"rootCause")} red /><ChipList title="Waste / Bottleneck" items={arr(room,"wasteTypes")} red /></section>
    <section style={goldCard}><div style={goldEye}>AI Routed Profile</div>{profile ? <div style={{ display: "grid", gridTemplateColumns: "minmax(120px,170px) 1fr", gap: 18, alignItems: "center" }}><div style={{ height: 150, borderRadius: 22, overflow: "hidden", border: "1px solid rgba(245,197,66,.28)", background: "rgba(255,255,255,.05)", display: "grid", placeItems: "center" }}>{profile.profilePhoto ? <img src={profile.profilePhoto} alt="Profile" style={{ width: "100%", height: "100%", objectFit: "cover" }} /> : <span style={{ color: "#ffd45a", fontWeight: 950 }}>No Photo</span>}</div><div><div style={goldEye}>Fit Score {score}/100</div><h2 style={{ fontSize: 34, margin: "0 0 8px" }}>{val(profile,"fullName","Saved Profile")}</h2><p style={sub}>{val(profile,"company","")} • {arr(profile,"memberTypes").join(", ") || "Member type not selected"}</p><p style={{ ...sub, fontSize: 17, marginTop: 10 }}>Contact: {arr(profile,"preferredContact").join(", ") || "not selected"} • {val(profile,"phone","")} {val(profile,"email","")}</p><p style={{ ...sub, fontSize: 17, marginTop: 10 }}>AI match reason: state/market fit, asset class fit, routing needs, capital/execution capabilities, and alert preferences from the saved profile.</p></div></div> : <p style={sub}>No saved profile found. Save `/profile` first so the room can auto-route member profile intelligence.</p>}</section>
    <section style={card}><div style={eyebrow}>Problem Details</div><div style={grid}><Fact label="Amount Needed" value={money(val(room,"amountNeeded",""))} /><Fact label="Property Value" value={money(val(room,"propertyValue",""))} /><Fact label="Payoff" value={money(val(room,"payoff",""))} /><Fact label="Arrears" value={money(val(room,"arrears",""))} /><Fact label="Deadline" value={val(room,"deadline")} /><Fact label="Authority" value={val(room,"authority")} /><Fact label="Occupancy" value={val(room,"occupancy")} /><Fact label="Access" value={val(room,"access")} /></div><ChipList title="Pain Types" items={arr(room,"painTypes")} red /><ChipList title="Urgency" items={arr(room,"urgency")} red /><ChipList title="Blockers" items={arr(room,"blockers")} red /><ChipList title="Routing Needs" items={arr(room,"routingNeeds")} /><ChipList title="Solution Lanes" items={arr(room,"solutionLanes")} /></section>
    <section style={goldCard}><div style={goldEye}>Asset Fields</div><div style={grid}><Fact label="Asset Class" value={val(room,"assetClass")} /><Fact label="Beds" value={val(room,"beds")} /><Fact label="Baths" value={val(room,"baths")} /><Fact label="Sqft" value={val(room,"sqft")} /><Fact label="Units" value={val(room,"units")} /><Fact label="Building Size" value={val(room,"buildingSize")} /><Fact label="Business / Asset Type" value={val(room,"businessType")} /><Fact label="Acres" value={val(room,"acres")} /><Fact label="Zoning" value={val(room,"zoning")} /><Fact label="Utilities" value={val(room,"utilities")} /></div></section>
    <section style={card}><div style={eyebrow}>Owner Contact</div><div style={grid}><Fact label="Name" value={val(room,"contactName")} /><Fact label="Phone" value={val(room,"contactPhone")} /><Fact label="Email" value={val(room,"contactEmail")} /><Fact label="Best Contact" value={val(room,"bestContact")} /><Fact label="Owner Role" value={val(room,"ownerRole")} /></div><div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginTop: 18 }}><Link href={`/messages?room=${encodeURIComponent(room.id)}&subject=${encodeURIComponent(subject)}`} style={goldBtn}>Message Owner</Link><span style={btn}>Subject: {subject}</span></div></section>
    <section style={card}><div style={eyebrow}>AI Execution Read</div><p style={sub}>{val(room,"aiRead","No AI read saved.")}</p><div style={{ ...goldCard, marginTop: 18, marginBottom: 0 }}><div style={goldEye}>Desired Outcome</div><p style={sub}>{val(room,"desiredOutcome","Not listed")}</p></div><div style={{ ...goldCard, marginTop: 18, marginBottom: 0 }}><div style={goldEye}>Private AI Notes</div><p style={sub}>{val(room,"privateAiNotes","No private notes saved.")}</p></div></section>
  </div></main>;
}
