"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

const DEAL_KEYS = ["vaultforge_clean_deal_rooms", "vaultforge_deal_rooms", "vaultforge_rooms_deals", "vf_deal_rooms"];
const PAIN_KEYS = ["vaultforge_clean_pain_rooms_v2", "vaultforge_clean_pain_rooms_v1", "vaultforge_clean_pain_rooms", "vaultforge_pain_rooms", "vaultforge_rooms_pain", "vf_pain_rooms"];
const MEMBER_KEYS = ["vaultforge_admin_members_v1", "vaultforge_members", "vaultforge_member_profiles", "vaultforge_profiles", "vf_profiles", "members", "profiles"];
const ALERT_KEYS = ["vaultforge_alerts_v1", "vaultforge_smart_alerts", "vf_alerts", "vaultforge_room_alerts"];
const ROUTE_STATUS_KEY = "vaultforge_route_status_v1";

type Metric = { label: string; value: number; note: string };

function ok() {
  return typeof window !== "undefined" && typeof window.localStorage !== "undefined";
}

function j<T>(raw: string | null, fallback: T): T {
  try {
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch {
    return fallback;
  }
}

function countArrayKeys(keys: string[]) {
  if (!ok()) return 0;
  let total = 0;
  for (const key of keys) {
    const parsed = j<unknown>(localStorage.getItem(key), []);
    if (Array.isArray(parsed)) total += parsed.length;
    else if (parsed && typeof parsed === "object") total += Object.keys(parsed as Record<string, unknown>).length;
  }
  return total;
}

function countRooms(kind: "deal" | "pain") {
  if (!ok()) return 0;
  const keys = kind === "deal" ? DEAL_KEYS : PAIN_KEYS;
  const seen = new Set<string>();

  for (const key of keys) {
    const parsed = j<unknown>(localStorage.getItem(key), []);
    if (Array.isArray(parsed)) {
      parsed.forEach((row: any, index) => seen.add(String(row?.id || row?.roomId || row?.dealId || row?.painId || row?.signalId || `${key}-${index}`)));
    } else if (parsed && typeof parsed === "object") {
      Object.entries(parsed as Record<string, any>).forEach(([id, row]) => seen.add(String(row?.id || row?.roomId || id)));
    }
  }

  for (let i = 0; i < localStorage.length; i += 1) {
    const key = localStorage.key(i) || "";
    const match = kind === "deal" ? key.includes("deal_room") || key.includes("deal_rooms") : key.includes("pain_room") || key.includes("pain_rooms");
    if (!match) continue;
    const parsed = j<any>(localStorage.getItem(key), null);
    if (Array.isArray(parsed)) {
      parsed.forEach((row, index) => seen.add(String(row?.id || row?.roomId || row?.dealId || row?.painId || row?.signalId || `${key}-${index}`)));
    } else if (parsed && typeof parsed === "object") {
      seen.add(String(parsed.id || parsed.roomId || key));
    }
  }

  return seen.size;
}

function routeCount() {
  if (!ok()) return 0;
  return Object.keys(j<Record<string, unknown>>(localStorage.getItem(ROUTE_STATUS_KEY), {})).length;
}

function currentEmail() {
  if (!ok()) return "";
  try {
    const profile = JSON.parse(localStorage.getItem("vaultforge_profile") || "{}");
    return String(profile.email || localStorage.getItem("vf_email") || localStorage.getItem("member_email") || "").trim().toLowerCase();
  } catch {
    return String(localStorage.getItem("vf_email") || localStorage.getItem("member_email") || "").trim().toLowerCase();
  }
}

const tickerItems = [
  "PAIN SIGNAL • STALLED PROJECT • GEORGIA",
  "CAPITAL GAP ROUTE • FLORIDA",
  "OPERATOR REQUEST • TENNESSEE",
  "OFF-MARKET OPPORTUNITY • NORTH CAROLINA",
  "DISTRESSED SELLER PRESSURE • ALABAMA",
  "LAND SIGNAL • TEXAS",
  "BUYER MATCH CREATED • SOUTH CAROLINA",
  "EXECUTION ROOM OPENED • ATLANTA",
  "VAULTFORGE INTELLIGENCE • ROUTE GENERATED",
  "MEMBER-TO-MEMBER SIGNAL • PRIVATE NETWORK",
];

const liveSignals = [
  "Distressed seller pressure detected",
  "Funding gap routed to capital lane",
  "Operator requested for stalled construction",
  "Deal room opened for private review",
  "Pain signal scored for execution risk",
  "Member match generated by route fit",
  "Private opportunity held behind access wall",
  "Admin approval required before full unlock",
];

const stateCards = [
  ["GA", "Georgia", "High", "Deal + Pain lanes active"],
  ["FL", "Florida", "High", "Capital and operator pressure"],
  ["TX", "Texas", "Building", "Land and buyer lanes"],
  ["TN", "Tennessee", "Active", "Operator route signals"],
  ["NC", "North Carolina", "Active", "Buyer and deal flow"],
  ["SC", "South Carolina", "Emerging", "Member network expansion"],
  ["AL", "Alabama", "Emerging", "Distress and operator signals"],
];

const page: React.CSSProperties = { minHeight: "100vh", background: "#05070d", color: "#f7f7fb", fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif", overflowX: "hidden" };
const wrap: React.CSSProperties = { maxWidth: 1380, margin: "0 auto", padding: "18px 18px 90px" };
const nav: React.CSSProperties = { display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", marginBottom: 18 };
const navSide: React.CSSProperties = { display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" };
const brand: React.CSSProperties = { color: "#ffd45a", fontSize: 28, fontWeight: 950, letterSpacing: -1 };
const btn: React.CSSProperties = { border: "1px solid rgba(207,216,230,.18)", background: "#171c29", color: "#f7f7fb", borderRadius: 999, padding: "13px 18px", fontWeight: 950, textDecoration: "none", display: "inline-block", cursor: "pointer" };
const goldBtn: React.CSSProperties = { ...btn, border: 0, background: "#ffdc68", color: "#10131a" };
const redBtn: React.CSSProperties = { ...btn, background: "#271016", borderColor: "rgba(255,70,70,.48)", color: "#ffaaaa" };
const hero: React.CSSProperties = { border: "1px solid rgba(245,197,66,.28)", borderRadius: 34, padding: "clamp(28px,5vw,58px)", marginBottom: 20, background: "radial-gradient(circle at top right, rgba(245,197,66,.18), transparent 34%), radial-gradient(circle at bottom left, rgba(255,45,60,.12), transparent 32%), linear-gradient(180deg,#080d19,#050816)", boxShadow: "0 0 55px rgba(245,197,66,.08)" };
const card: React.CSSProperties = { background: "linear-gradient(180deg,#080d19,#050816)", border: "1px solid rgba(245,197,66,.28)", borderRadius: 30, padding: 28, marginBottom: 22 };
const panel: React.CSSProperties = { background: "#121724", border: "1px solid rgba(207,216,230,.16)", borderRadius: 24, padding: 22, color: "#f7f7fb", textDecoration: "none", display: "block" };
const goldPanel: React.CSSProperties = { ...panel, borderColor: "rgba(245,197,66,.55)", boxShadow: "0 0 28px rgba(245,197,66,.12)" };
const redPanel: React.CSSProperties = { ...panel, borderColor: "rgba(255,70,70,.56)", boxShadow: "0 0 28px rgba(255,70,70,.10)" };
const eyebrow: React.CSSProperties = { color: "#ffd45a", textTransform: "uppercase", letterSpacing: 7, fontWeight: 950, fontSize: 13, marginBottom: 12 };
const h1: React.CSSProperties = { fontSize: "clamp(52px,11vw,128px)", lineHeight: 0.82, letterSpacing: -6, margin: "0 0 20px", fontWeight: 950 };
const h2: React.CSSProperties = { fontSize: "clamp(34px,6vw,70px)", lineHeight: 0.92, letterSpacing: -3, margin: "0 0 16px", fontWeight: 950 };
const h3: React.CSSProperties = { fontSize: "clamp(25px,4vw,42px)", lineHeight: 1, letterSpacing: -1.5, margin: "0 0 12px", fontWeight: 950 };
const sub: React.CSSProperties = { color: "#c9d0dc", fontSize: "clamp(19px,2.5vw,26px)", lineHeight: 1.28, margin: 0 };
const muted: React.CSSProperties = { color: "#aeb7c7", margin: "8px 0 0", lineHeight: 1.35 };
const grid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(250px,1fr))", gap: 16 };
const wideGrid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(320px,1fr))", gap: 18 };
const row: React.CSSProperties = { display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" };
const badge: React.CSSProperties = { display: "inline-flex", border: "1px solid rgba(245,197,66,.32)", borderRadius: 999, padding: "9px 13px", color: "#ffd45a", background: "rgba(245,197,66,.07)", fontWeight: 900, margin: "6px 6px 0 0" };
const tickerWrap: React.CSSProperties = { borderTop: "1px solid rgba(245,197,66,.25)", borderBottom: "1px solid rgba(245,197,66,.25)", background: "#090d14", overflow: "hidden", marginBottom: 20 };
const tickerTrack: React.CSSProperties = { display: "flex", gap: 40, width: "max-content", padding: "14px 0", animation: "tickerMove 38s linear infinite" };

function Nav({ owner }: { owner: boolean }) {
  return (
    <nav style={nav}>
      <div style={navSide}>
        <div style={brand}>VAULTFORGE</div>
        <span style={badge}>PRIVATE APPROVED ACCESS ONLY</span>
      </div>
      <div style={navSide}>
        <Link href="/member-access" style={goldBtn}>Member Access</Link>
        <Link href="/command" style={btn}>Member Command</Link>
        {owner ? <Link href="/admin" style={redBtn}>Admin Command</Link> : <Link href="/create-login" style={btn}>Create Login</Link>}
      </div>
    </nav>
  );
}

function Ticker() {
  return (
    <div style={tickerWrap}>
      <div style={tickerTrack}>
        {[...tickerItems, ...tickerItems].map((item, index) => (
          <div key={`${item}-${index}`} style={{ whiteSpace: "nowrap", color: "#ffd45a", fontWeight: 950, letterSpacing: 3 }}>{item}</div>
        ))}
      </div>
    </div>
  );
}

function MetricCard({ metric }: { metric: Metric }) {
  return (
    <div style={goldPanel}>
      <div style={eyebrow}>{metric.label}</div>
      <h2 style={h2}>{metric.value}</h2>
      <p style={muted}>{metric.note}</p>
    </div>
  );
}

function Section({ eyebrowText, title, children }: { eyebrowText: string; title: string; children: React.ReactNode }) {
  return <section style={card}><div style={eyebrow}>{eyebrowText}</div><h2 style={h2}>{title}</h2>{children}</section>;
}

function FlowCard({ number, title, body }: { number: string; title: string; body: string }) {
  return <div style={panel}><div style={eyebrow}>{number}</div><h3 style={h3}>{title}</h3><p style={muted}>{body}</p></div>;
}

export default function HomePage() {
  const [tick, setTick] = useState(0);
  const [owner, setOwner] = useState(false);

  useEffect(() => {
    const refresh = () => {
      setOwner(currentEmail() === "bcrsoutheast@gmail.com");
      setTick((value) => value + 1);
    };
    refresh();
    window.addEventListener("storage", refresh);
    window.addEventListener("vaultforge-admin-members-change", refresh);
    window.addEventListener("vaultforge-alert-change", refresh);
    window.addEventListener("vaultforge-route-status-change", refresh);
    window.addEventListener("vaultforge-my-rooms-change", refresh);
    return () => {
      window.removeEventListener("storage", refresh);
      window.removeEventListener("vaultforge-admin-members-change", refresh);
      window.removeEventListener("vaultforge-alert-change", refresh);
      window.removeEventListener("vaultforge-route-status-change", refresh);
      window.removeEventListener("vaultforge-my-rooms-change", refresh);
    };
  }, []);

  const metrics = useMemo<Metric[]>(() => {
    const dealCount = countRooms("deal");
    const painCount = countRooms("pain");
    const members = Math.max(countArrayKeys(MEMBER_KEYS), owner ? 1 : 0);
    return [
      { label: "Approved Members", value: members, note: "private network access" },
      { label: "Opportunity Rooms", value: dealCount, note: "deal intelligence rooms" },
      { label: "Pain Signals", value: painCount, note: "problem pressure entering the network" },
      { label: "Routing Events", value: routeCount(), note: "member-to-member route activity" },
      { label: "Signal Alerts", value: countArrayKeys(ALERT_KEYS), note: "market and execution pressure" },
      { label: "Active States", value: 7, note: "Southeast and expansion markets" },
    ];
  }, [tick, owner]);

  return (
    <main style={page}>
      <style>{`@keyframes tickerMove { 0% { transform: translateX(0); } 100% { transform: translateX(-50%); } }`}</style>
      <div style={wrap}>
        <Nav owner={owner} />

        <section style={hero}>
          <div style={eyebrow}>VaultForge Intelligence</div>
          <h1 style={h1}>Pain becomes signal.</h1>
          <p style={sub}>VaultForge is not a listings site. It is a private approved-member intelligence, routing, and execution network for real estate operators, buyers, lenders, partners, and problem solvers.</p>
          <div style={{ ...row, marginTop: 24 }}>
            <Link href="/member-access" style={goldBtn}>Request Member Access</Link>
            <Link href="/create-login" style={btn}>Create Login</Link>
            <Link href="/contact-admin" style={btn}>Contact Admin</Link>
            {owner ? <Link href="/admin" style={redBtn}>Admin Command</Link> : null}
          </div>
          <div style={{ marginTop: 24 }}>
            <span style={badge}>PRIVATE NETWORK</span>
            <span style={badge}>APPROVED MEMBERS ONLY</span>
            <span style={badge}>PAIN → SIGNAL → ROUTING → EXECUTION</span>
          </div>
        </section>

        <Ticker />

        <section style={{ marginBottom: 22 }}><div style={grid}>{metrics.map((metric) => <MetricCard key={metric.label} metric={metric} />)}</div></section>

        <Section eyebrowText="Not Real Estate Listings" title="This is private execution infrastructure.">
          <p style={sub}>Most platforms show finished listings after the market already sees them. VaultForge surfaces real-world pressure, routes the signal, and connects approved members before the opportunity becomes public noise.</p>
          <div style={{ ...grid, marginTop: 20 }}>
            <div style={panel}><div style={eyebrow}>Not A Marketplace</div><p style={sub}>VaultForge is not built for public browsing, mass posting, or open listings.</p></div>
            <div style={panel}><div style={eyebrow}>Not Social Media</div><p style={sub}>Members connect through routed intelligence, not random feeds or public chatter.</p></div>
            <div style={panel}><div style={eyebrow}>Not Lead Lists</div><p style={sub}>Signals are routed by fit, execution need, capital, pressure, and member capability.</p></div>
          </div>
        </Section>

        <Section eyebrowText="Pain Intelligence" title="Pain is where opportunity begins.">
          <p style={sub}>Pain means a real-world problem requiring execution: capital gaps, stalled construction, distressed sellers, lender pressure, permit issues, tenant problems, operator needs, emergency exits, off-market opportunities, or partnership breakdowns.</p>
          <div style={{ marginTop: 18 }}>
            {["DISTRESSED SELLER", "FUNDING GAP", "STALLED PROJECT", "OPERATOR NEEDED", "TITLE / LEGAL ISSUE", "CITY / PERMIT PROBLEM", "LAND PRESSURE", "BUYER MATCH", "EMERGENCY EXIT", "CAPITAL REQUEST", "CONTRACTOR PROBLEM", "PORTFOLIO LIQUIDATION"].map((item) => <span key={item} style={badge}>{item}</span>)}
          </div>
        </Section>

        <Section eyebrowText="Core Engine" title="Pain → Signal → Routing → Execution">
          <div style={wideGrid}>
            <FlowCard number="01" title="Pain / Opportunity" body="A member submits a deal, opportunity, pressure point, capital need, operator request, or execution problem." />
            <FlowCard number="02" title="VaultForge Signal" body="VaultForge Intelligence classifies the situation, identifies risk, urgency, service need, and execution path." />
            <FlowCard number="03" title="Private Routing" body="The signal is routed to the members, buyers, lenders, contractors, operators, or partners positioned to help." />
            <FlowCard number="04" title="Execution" body="Members connect directly through rooms, messages, alerts, and route queues to move the situation forward." />
          </div>
        </Section>

        <section style={wideGrid}>
          <section style={card}>
            <div style={eyebrow}>Live Signal Feed</div>
            <h2 style={h2}>Network activity.</h2>
            <div style={{ display: "grid", gap: 12 }}>
              {liveSignals.map((item, index) => <div key={item} style={index < 2 ? redPanel : panel}><div style={eyebrow}>Live Signal {String(index + 1).padStart(2, "0")}</div><p style={sub}>{item}</p></div>)}
            </div>
          </section>
          <section style={card}>
            <div style={eyebrow}>State Pressure Map</div>
            <h2 style={h2}>Active markets.</h2>
            <div style={grid}>
              {stateCards.map(([code, label, pressure, note]) => <div key={code} style={pressure === "High" ? redPanel : goldPanel}><div style={eyebrow}>{label}</div><h2 style={h2}>{code}</h2><p style={sub}>{pressure}</p><p style={muted}>{note}</p></div>)}
            </div>
          </section>
        </section>

        <Section eyebrowText="Approved Member Network" title="Member-to-member execution, not public exposure.">
          <div style={grid}>
            {[
              ["Buyers", "Acquire routed opportunities and respond to execution signals."],
              ["Operators", "Solve stalled projects, management gaps, rehab needs, and field problems."],
              ["Lenders", "Respond to capital pressure, gap funding, refinance, and rescue needs."],
              ["Developers", "Review land, entitlement, zoning, and project execution opportunities."],
              ["Contractors", "Support construction, repair, rehab, and emergency work."],
              ["Wholesalers", "Submit controlled opportunities into private routing instead of public noise."],
              ["Capital Partners", "Review risk-adjusted opportunities and pressure situations."],
              ["Problem Solvers", "Move pain from signal to execution outcome."],
            ].map(([title, body]) => <div key={title} style={panel}><div style={eyebrow}>{title}</div><h3 style={h3}>{title}</h3><p style={muted}>{body}</p></div>)}
          </div>
        </Section>

        <Section eyebrowText="Access Flow" title="Private access is controlled.">
          <div style={wideGrid}>
            <FlowCard number="01" title="Create Login" body="Start with email and password to create your member identity." />
            <FlowCard number="02" title="Complete Profile" body="Tell VaultForge what you do, where you operate, and how you execute." />
            <FlowCard number="03" title="Admin Approval" body="Owner reviews your profile before payment access is opened." />
            <FlowCard number="04" title="Payment Unlock" body="Once approved and paid, the full member execution network unlocks." />
          </div>
          <div style={{ ...row, marginTop: 24 }}>
            <Link href="/member-access" style={goldBtn}>Start Member Access</Link>
            <Link href="/contact-admin" style={btn}>Contact Admin</Link>
            <Link href="/command" style={btn}>Member Command</Link>
          </div>
        </Section>

        <section style={hero}>
          <div style={eyebrow}>VaultForge Intelligence</div>
          <h2 style={h2}>See pressure before the market does.</h2>
          <p style={sub}>Not every opportunity should become public. Not every problem belongs on the open market. VaultForge exists to coordinate execution before the rest of the market sees the pressure.</p>
          <div style={{ ...row, marginTop: 22 }}>
            <Link href="/member-access" style={goldBtn}>Request Access</Link>
            {owner ? <Link href="/admin" style={redBtn}>Admin Command</Link> : <Link href="/create-login" style={btn}>Create Login</Link>}
          </div>
        </section>
      </div>
    </main>
  );
}
