create table if not exists public.vault_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,

  -- Link to deal or pain
  deal_id bigint references public.deals(id) on delete cascade,
  pain_deal_id bigint references public.pain_deals(id) on delete cascade,

  -- Message data
  sender_type text not null, -- 'user' or 'seller'
  message_text text not null,
  is_read boolean default false,
  created_at timestamp with time zone default now(),

  constraint one_thread_type check (
    (deal_id is not null and pain_deal_id is null) or
    (deal_id is null and pain_deal_id is not null)
  )
);

alter table public.vault_messages enable row level security;
create policy "Users CRUD own messages" on public.vault_messages for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Add unread count tracking
alter table public.deals add column if not exists unread_message_count int default 0;
alter table public.pain_deals add column if not exists unread_message_count int default 0;
