-- 1. Members table
create table if not exists public.vault_members (
  id uuid references auth.users primary key,
  full_name text not null,
  email text not null,
  phone text,
  state_from text not null, -- State they live in, not where they invest
  city text,
  bio text,
  avatar_url text,
  deals_closed int default 0,
  verified boolean default false,
  created_at timestamp with time zone default now()
);

alter table public.vault_members enable row level security;
create policy "Members visible to all logged in users" on public.vault_members for select using (auth.uid() is not null);
create policy "Users update own profile" on public.vault_members for update using (auth.uid() = id);

-- 2. Saved members table
create table if not exists public.saved_members (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  member_id uuid references public.vault_members(id) not null,
  created_at timestamp with time zone default now(),
  unique(user_id, member_id)
);

alter table public.saved_members enable row level security;
create policy "Users CRUD own saved members" on public.saved_members for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 3. Deleted/hidden members table
create table if not exists public.hidden_members (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  member_id uuid references public.vault_members(id) not null,
  created_at timestamp with time zone default now(),
  unique(user_id, member_id)
);

alter table public.hidden_members enable row level security;
create policy "Users CRUD own hidden members" on public.hidden_members for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 4. Member messages table
create table if not exists public.member_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  message_text text not null,
  is_read boolean default false,
  created_at timestamp with time zone default now()
);

alter table public.member_messages enable row level security;
create policy "Users see own messages" on public.member_messages for select using (auth.uid() = sender_id or auth.uid() = receiver_id);
create policy "Users send messages" on public.member_messages for insert with check (auth.uid() = sender_id);
