"use client";

import React, { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";

type RoomState = "active" | "saved" | "archived" | "deleted";
type DealRoom = Record<string, any> & { id: string; roomState?: RoomState };
type Profile = Record<string, any>;

const ROOM_KEYS = ["vaultforge_clean_deal_rooms", "vaultforge_deal_rooms", "vaultforge_rooms_deals", "vf_deal_rooms"];
const STATE_KEY = "vaultforge_clean_room_states";
const PROFILE_KEY = "vaultforge_profile_v2";

const page: React.CSSProperties = { minHeight: "100vh", background: "#05070d", color: "#f7f7fb", padding: 18, fontFamily: "Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif" };
const wrap: React.CSSProperties = { maxWidth: 1180, margin: "0 auto", paddingBottom: 70 };
const card: React.CSSProperties = { background: "linear-gradient(180deg,#080d19,#050816)", border: "1px solid rgba(245,197,66,.28)", borderRadius: 26, padding: 28, marginBottom: 22 };
const eyebrow: React.CSSProperties = { color: "#ffd45a", textTransform: "uppercase", letterSpacing: 8, fontWeight: 900, fontSize: 14, marginBottom: 14 };
const h1: React.CSSProperties = { fontSize: "clamp(42px,7vw,72px)", lineHeight: .92, letterSpacing: -4, margin: "0 0 18px", fontWeight: 950 };
const sub: React.CSSProperties = { color: "#c9d0dc", fontSize: 20, lineHeight: 1.4, margin: 0 };
const grid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(245px,1fr))", gap: 16 };
const btn: React.CSSProperties = { border: "1px solid rgba(207,216,230,.18)", background: "#171c29", color: "#f7f7fb", borderRadius: 999, padding: "13px 18px", fontWeight: 950, textDecoration: "none", display: "inline-block", cursor: "pointer" };
const goldBtn: React.CSSProperties = { ...btn, border: 0, background: "#ffdc68", color: "#10131a" };
const redBtn: React.CSSProperties = { ...btn, background: "#271016", borderColor: "rgba(255,70,70,.48)", color: "#ffaaaa" };

function readJson<T>(key: string, fallback: T): T { try { const raw = window.localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch { return fallback; } }
function writeJson(key: string, value: any) { window.localStorage.setItem(key, JSON.stringify(value)); }
function getStates(): Record<string, RoomState> { return readJson(STATE_KEY, {} as Record<string, RoomState>); }
function dealId(deal: DealRoom) { return String(deal.id || deal.roomId || deal.dealId || ""); }
function readArray(key: string): DealRoom[] { return readJson<DealRoom[]>(key, []); }
function val(deal: DealRoom | null, keys: string[], fallback = "Not listed") { for (const k of keys) { const v = deal?.[k]; if (v !== undefined && v !== null && String(v).trim()) return String(v); } return fallback; }
function arr(deal: DealRoom | null, keys: string[]) { for (const k of keys) { const v = deal?.[k]; if (Array.isArray(v)) return v.map(String); if (typeof v === "string" && v.trim()) return v.split(",").map((x) => x.trim()).filter(Boolean); } return []; }
function money(v: string) { const clean = String(v || "").replace(/[^0-9.]/g, ""); if (!clean) return "Not listed"; const n = Number(clean); return Number.isFinite(n) ? `$${n.toLocaleString()}` : v; }
function photo(deal: DealRoom | null) { return val(deal, ["photoUrl", "photoURL", "imageUrl", "publicUrl", "photo", "photoDataUrl", "image", "thumbnailUrl"], ""); }
function profile(): Profile { return readJson<Profile>(PROFILE_KEY, {}); }
function findDeal(id: string): DealRoom | null { const states = getStates(); for (const key of ROOM_KEYS) { const hit = readArray(key).find((deal) => dealId(deal) === id); if (hit) return { ...hit, id, roomState: states[id] || hit.roomState || "active" }; } for (const key of [`vaultforge_clean_deal_room_${id}`, `vaultforge_deal_room_${id}`, `vf_deal_room_${id}`]) { const hit = readJson<DealRoom | null>(key, null); if (hit) return { ...hit, id, roomState: states[id] || hit.roomState || "active" }; } return null; }
function syncDeal(deal: DealRoom) { const id = dealId(deal); if (!id) return; writeJson(`vaultforge_clean_deal_room_${id}`, deal); writeJson(`vaultforge_deal_room_${id}`, deal); writeJson(`vf_deal_room_${id}`, deal); ROOM_KEYS.forEach((key) => { const rows = readArray(key).filter((item) => dealId(item) !== id); writeJson(key, [deal, ...rows]); }); window.dispatchEvent(new Event("vaultforge-deal-change")); }
function score(deal: DealRoom, p: Profile) { let points = 0; const reasons: string[] = []; const state = val(deal,["state"],""); const county = val(deal,["county"],""); const asset = val(deal,["assetClass","assetType"],""); const routes = arr(deal,["routeTo","routedTo"]); const strategy = arr(deal,["strategies","dealTypes"]); const states = [...(p.buyStates || []), ...(p.operateStates || []), ...(p.alertStates || []), ...(p.contactStates || [])]; if (state && states.includes(state)) { points += 20; reasons.push(`${state} state match`); } if (county && p.countiesByState?.[state]?.includes?.(county)) { points += 20; reasons.push(`${county} county match`); } if (asset && (p.assetTypes || []).some((x: string) => asset.toLowerCase().includes(String(x).toLowerCase()) || String(x).toLowerCase().includes(asset.toLowerCase()))) { points += 20; reasons.push(`${asset} asset match`); } routes.forEach((r) => { if ((p.memberTypes || []).includes(r) || (p.capitalRoles || []).includes(r)) { points += 10; reasons.push(`${r} lane match`); } }); strategy.forEach((s) => { if ((p.dealTypes || []).includes(s)) { points += 8; reasons.push(`${s} strategy match`); } }); if ((p.routingRules || []).includes("Allow AI Routing")) { points += 12; reasons.push("AI routing allowed"); } return { points: Math.min(100, points || 38), reasons: reasons.length ? reasons : ["Profile saved, but needs more buy-box chips for higher confidence."] }; }
function Fact({ label, value }: { label: string; value: string }) { return <div style={{ background: "#121724", border: "1px solid rgba(207,216,230,.14)", borderRadius: 20, padding: 20 }}><div style={{ ...eyebrow, fontSize: 12, letterSpacing: 4 }}>{label}</div><div style={{ fontSize: 22, fontWeight: 850 }}>{value || "Not listed"}</div></div>; }
function PillList({ title, values }: { title: string; values: string[] }) { return <section style={{ ...card, padding: 22 }}><div style={eyebrow}>{title}</div><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{values.length ? values.map((x)=><span key={x} style={{border:"1px solid rgba(245,197,66,.24)",background:"rgba(245,197,66,.07)",color:"#ffe99a",borderRadius:999,padding:"9px 12px",fontWeight:900,fontSize:13}}>{x}</span>) : <span style={{color:"#c9d0dc"}}>Not listed</span>}</div></section>; }

export default function DealRoomDetailPage() {
  const params = useParams(); const id = decodeURIComponent(String(params?.id || ""));
  const [deal, setDeal] = useState<DealRoom | null>(null);
  const [p, setP] = useState<Profile>({});
  function load() { setDeal(findDeal(id)); setP(profile()); }
  useEffect(() => { load(); }, [id]);
  function setRoomState(state: RoomState) { if (!deal) return; const states = getStates(); states[id] = state; writeJson(STATE_KEY, states); const next = { ...deal, roomState: state, updatedAt: new Date().toISOString() }; syncDeal(next); setDeal(next); }
  const img = photo(deal); const routes = arr(deal,["routeTo","routedTo"]); const issues = arr(deal,["knownIssues","issues"]); const docs = arr(deal,["docs"]); const strategies = arr(deal,["strategies","dealTypes"]); const capitalNeeds = arr(deal,["capitalNeeds"]); const fit = useMemo(() => deal ? score(deal, p) : { points: 0, reasons: [] as string[] }, [deal, p]);
  const profileName = [p.fullName, p.company].filter(Boolean).join(" / ") || "No saved member profile";
  const profilePhoto = String(p.profilePhoto || p.companyLogo || "");
  const signalSummary = deal ? val(deal, ["signalSummary"], `${val(deal,["assetClass"],"Deal")} signal in ${[val(deal,["city"],""), val(deal,["county"],""), val(deal,["state"],"")].filter(Boolean).join(", ")}. Ask ${money(val(deal,["askingPrice","ask"],""))}, value ${money(val(deal,["arv","value"],""))}, repairs ${money(val(deal,["repairs"],""))}.`) : "";
  if (!deal) return <main style={page}><div style={wrap}><Link href="/deal-rooms" style={goldBtn}>Back to Deal Rooms</Link><section style={card}><div style={eyebrow}>Deal Room</div><h1 style={h1}>Room not found.</h1><p style={sub}>Open a saved Deal Room from the board.</p></section></div></main>;
  return <main style={page}><div style={wrap}>
    <nav style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:18}}><Link href="/command" style={btn}>Command</Link><Link href="/deal-rooms" style={goldBtn}>Deal Rooms</Link><Link href="/messages" style={btn}>Messages</Link><Link href="/profile" style={btn}>Profile</Link><Link href="/" style={redBtn}>Exit</Link></nav>
    <section style={card}>{img ? <img src={img} alt={val(deal,["title"],"Deal photo")} style={{width:"100%",maxHeight:440,objectFit:"cover",borderRadius:24,marginBottom:24,border:"1px solid rgba(207,216,230,.2)"}} /> : <div style={{border:"1px dashed rgba(207,216,230,.25)",borderRadius:24,padding:70,textAlign:"center",color:"#c9d0dc",marginBottom:24}}>No photo URL saved for this room</div>}<div style={eyebrow}>{val(deal,["assetClass","asset_class"],"Deal Room")}</div><h1 style={h1}>{val(deal,["title","name"],"Untitled Deal")}</h1><p style={sub}>{[val(deal,["city"],""), val(deal,["county"],""), val(deal,["state"],"")].filter(Boolean).join(" • ")}</p></section>
    <section style={card}><div style={eyebrow}>5S Controls</div><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button type="button" onClick={()=>setRoomState("saved")} style={goldBtn}>Save</button><button type="button" onClick={()=>setRoomState("archived")} style={btn}>Archive</button><button type="button" onClick={()=>setRoomState("deleted")} style={redBtn}>Delete</button><span style={btn}>Current: {deal.roomState || "active"}</span></div></section>
    <section style={card}><div style={eyebrow}>VaultForge Signal Summary</div><p style={sub}>{signalSummary}</p></section>
    <section style={card}><div style={eyebrow}>AI Routed Profile</div><div style={{display:"grid",gridTemplateColumns:"140px minmax(0,1fr)",gap:18,alignItems:"center"}}><div style={{width:132,height:132,borderRadius:24,overflow:"hidden",border:"1px solid rgba(245,197,66,.28)",background:"#111827",display:"grid",placeItems:"center",color:"#c9d0dc",fontWeight:950}}>{profilePhoto ? <img src={profilePhoto} alt="Profile" style={{width:"100%",height:"100%",objectFit:"cover"}}/> : "No photo"}</div><div><h2 style={{fontSize:36,margin:"0 0 8px"}}>{profileName}</h2><p style={sub}>Fit score: <strong style={{color:"#ffd45a"}}>{fit.points}%</strong>. Contact: {(p.preferredContact || []).join(", ") || "Not selected"}. Phone: {p.phone || "Not listed"}. Email: {p.email || "Not listed"}.</p><div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:12}}>{fit.reasons.map((r)=><span key={r} style={{border:"1px solid rgba(245,197,66,.24)",borderRadius:999,padding:"8px 11px",color:"#ffe99a",fontWeight:900,fontSize:12}}>{r}</span>)}</div></div></div><div style={{...grid,marginTop:18}}><Fact label="Member Types" value={(p.memberTypes || []).join(", ") || "Not listed"}/><Fact label="Buy States" value={(p.buyStates || []).join(", ") || "Not listed"}/><Fact label="Alert States" value={(p.alertStates || []).join(", ") || "Not listed"}/><Fact label="Capital Role" value={(p.capitalRoles || []).join(", ") || "Not listed"}/><Fact label="Execution" value={(p.executionCapabilities || []).join(", ") || "Not listed"}/><Fact label="Routing Rules" value={(p.routingRules || []).join(", ") || "Not listed"}/></div></section>
    <section style={card}><div style={eyebrow}>Numbers + Asset Facts</div><div style={grid}><Fact label="Ask" value={money(val(deal,["askingPrice","ask"],""))}/><Fact label="ARV / Value" value={money(val(deal,["arv","value"],""))}/><Fact label="Repairs / Work" value={money(val(deal,["repairs"],""))}/><Fact label="Equity Spread" value={val(deal,["equitySpread"])}/><Fact label="Beds" value={val(deal,["beds"])}/><Fact label="Baths" value={val(deal,["baths"])}/><Fact label="Sqft" value={val(deal,["sqft"])}/><Fact label="Units" value={val(deal,["units"])}/><Fact label="Acres" value={val(deal,["acres"])}/><Fact label="Zoning" value={val(deal,["zoning"])}/></div></section>
    <section style={card}><div style={eyebrow}>Contact + Control</div><div style={grid}><Fact label="Name" value={val(deal,["contactName"])}/><Fact label="Phone" value={val(deal,["contactPhone"])}/><Fact label="Email" value={val(deal,["contactEmail"])}/><Fact label="Best Contact" value={val(deal,["bestContact"])}/><Fact label="Submitter Role" value={val(deal,["submitterRole"])}/><Fact label="Deadline" value={val(deal,["deadline"])}/></div></section>
    <div style={grid}><PillList title="Route Lanes" values={routes}/><PillList title="Strategy" values={strategies}/><PillList title="Capital Need" values={capitalNeeds}/><PillList title="Issues" values={issues}/><PillList title="Documents" values={docs}/><PillList title="AI Fit Reasons" values={fit.reasons}/></div>
    <section style={card}><div style={eyebrow}>AI Execution Brain</div><div style={grid}><Fact label="Urgency" value={val(deal,["urgency"])}/><Fact label="Occupancy" value={val(deal,["occupancy"])}/><Fact label="Access" value={val(deal,["access"])}/><Fact label="Assignment Fee" value={val(deal,["assignmentFee"])}/></div><div style={{...card,marginTop:20,marginBottom:0,padding:22}}><div style={eyebrow}>AI Room Read</div><p style={sub}>{val(deal,["aiRead"],"No AI read saved.")}</p></div><div style={{...card,marginTop:20,marginBottom:0,padding:22}}><div style={eyebrow}>Seller Motivation</div><p style={sub}>{val(deal,["sellerMotivation"],"Not listed")}</p></div><div style={{...card,marginTop:20,marginBottom:0,padding:22}}><div style={eyebrow}>Risk Notes</div><p style={sub}>{val(deal,["riskNotes"],"Not listed")}</p></div><div style={{...card,marginTop:20,marginBottom:0,padding:22}}><div style={eyebrow}>Private AI Notes</div><p style={sub}>{val(deal,["privateAiNotes","notes"],"No notes saved.")}</p></div></section>
  </div></main>;
}
